### ISSUE TITLE
Invalid polygons now crash the import process

### ISSUE THREAD

**Issue by pablocm** [OSMNames/OSMNames#187]
Greetings,
When using the latest commit of the master branch (#e66a0e9), it now crashes when an invalid (self-intersecting) geometry is present in the PBF dump.

I've checked my database and some of the offending OSM rows are (some have been recently fixed though):
https://www.openstreetmap.org/way/376238747
https://www.openstreetmap.org/way/518055940
https://www.openstreetmap.org/way/571463061
https://www.openstreetmap.org/way/414741599

I've been working with an older dump, and prior versions did not have this issue. I believe the bug was introduced in merge request https://github.com/OSMNames/OSMNames/pull/186.

For now I'm adding the following workaround in my local copy:
```
DELETE FROM osm_polygon WHERE st_isvalid(geometry) IS NOT TRUE;
```

Here's the log file right before the crash:
```
2019-05-24 18:51:31,217 - INFO - start executing sql file set_country_codes.sql

psql:/osmnames/osmnames/prepare_data/set_country_codes.sql:38: ERROR:  lwgeom_intersection: GEOS Error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -7507648.6665954227 5685173.000435628 at -7507648.6665954227 5685173.000435628
CONTEXT:  SQL statement "SELECT (
    SELECT lower(country_code)
    FROM country_osm_grid
    WHERE st_intersects(geometry, geometry_in)
    ORDER BY st_area(st_intersection(geometry, geometry_in)) DESC
    LIMIT 1
  )"
PL/pgSQL function get_most_intersecting_country_code(geometry) line 3 at RETURN
skip database init, since it is already initialized
Traceback (most recent call last):
  File "./run.py", line 30, in <module>
    run()
  File "./run.py", line 24, in run
    prepare_data()
  File "/osmnames/osmnames/prepare_data/prepare_data.py", line 12, in prepare_data
    set_country_codes()
  File "/osmnames/osmnames/prepare_data/prepare_data.py", line 64, in set_country_codes
    exec_sql_from_file("set_country_codes.sql", cwd=os.path.dirname(__file__))
  File "/osmnames/osmnames/database/functions.py", line 20, in exec_sql_from_file
    ], stdout=open(os.devnull, 'w')
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['psql', '-v', 'ON_ERROR_STOP=1', '--username=osm', '--dbname=osm', '--file=/osmnames/osmnames/prepare_data/set_country_codes.sql']' returned non-zero exit status 3
```

**Comment by sfkeller** [comment]
Instead of deleting invalid geometries, you could sanitize them with the ST_Buffer zero trick: 

```
UPDATE osm_polygon 
  SET geometry = ST_Multi(ST_Buffer(geometry, 0));
```

See e.g. http://revenant.ca/www/postgis/workshop/equality.html . Wondering if this works.
