### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AmilaViduranga** [OSMNames/OSMNames#190]
hi team,

I got bellow snap shot issue when I run the instructions. I have added "PBF_FILE=muve.osm.pbf"  in ".env"  file and added that file to the "data/import" folder

![image](https://user-images.githubusercontent.com/13863481/65874970-34b61280-e3a4-11e9-9220-077c07206678.png)

please give help me to solve this

**Comment by philippks** [comment]
hi @AmilaViduranga 

looks like an error in the [imposm import](muve.osm.pbf).

Could you provide the muve.osm.pbf file you're trying to import?

**Comment by AmilaViduranga** [comment]
hi @philippks ,

Inside this compressed folder my pbf file included. This is a merged with 2 osm files with help of https://osmcode.org/osmium-tool/
file:///home/amila/projects/OSM/map_osms/osm-20190814T084416Z-001/osm/Final_maps/Muve.osm.zip

**Comment by philippks** [comment]
@AmilaViduranga the file way not uploaded correctly. It only added the file path. Could you retry?

**Comment by AmilaViduranga** [comment]
sorry for my mistake, I have edited the commit

here is the driver link
https://drive.google.com/file/d/1X4UlOPCezo4xzdZM8iYX52htOIMieSJS/view?usp=sharing

**Comment by philippks** [comment]
@AmilaViduranga 

After downloading the newest imposm version I reproduced the error with:
```
# start a postgres / postigis db
docker run --name tmp-postgis -p 5432:5432 --rm -e POSTGRES_PASSWORD=password -e POSTGRES_DB=imposm_import -d mdillon/postgis
./imposm import -connection postgis://postgres:password@localhost/imposm_import -mapping mapping.json -read muve.osm.pbf -write -overwritecache
```

and I received the same error:
```
[2019-10-11T14:54:44+02:00] 0:00:00 [info] removing existing cache /tmp/imposm3
[2019-10-11T14:54:44+02:00] 0:00:00 [step] Starting: Imposm
[2019-10-11T14:54:44+02:00] 0:00:00 [step] Starting: Reading OSM data
[2019-10-11T14:54:44+02:00] 0:00:00 [info] reading muve.osm.pbf with data till 0001-01-01 00:29:46 +0029 BMT
[2019-10-11T14:55:33+02:00] 0:00:49 [progress]    49s C:       0/s (14582264) N:       0/s (65776) W:       0/s (2143921) R:      0/s (3002)
[2019-10-11T14:55:33+02:00] 0:00:49 [step] Finished: Reading OSM data in 49.30059502s
[2019-10-11T14:55:33+02:00] 0:00:49 [step] Starting: Importing OSM data
[2019-10-11T14:55:33+02:00] 0:00:49 [step] Starting: Writing OSM data
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x579b96]

goroutine 125 [running]:
github.com/omniscale/imposm3/cache.(*coordsBunch).GetCoord(0x0, 0xffffffffffffffda, 0x6, 0xc002a64d20, 0x0)
	/home/travis/gopath/src/github.com/omniscale/imposm3/cache/delta.go:27 +0x26
github.com/omniscale/imposm3/cache.(*DeltaCoordsCache).FillWay(0xc0000ab980, 0xc001d84280, 0xc00192d180, 0x1)
	/home/travis/gopath/src/github.com/omniscale/imposm3/cache/delta.go:187 +0x160
github.com/omniscale/imposm3/writer.(*WayWriter).loop.func1(0xc001d84280, 0xc001d84280)
	/home/travis/gopath/src/github.com/omniscale/imposm3/writer/ways.go:83 +0x56
github.com/omniscale/imposm3/writer.(*WayWriter).loop(0xc0010e4c80)
	/home/travis/gopath/src/github.com/omniscale/imposm3/writer/ways.go:98 +0x510
created by github.com/omniscale/imposm3/writer.(*OsmElemWriter).Start
	/home/travis/gopath/src/github.com/omniscale/imposm3/writer/writer.go:52 +0x81
```

So, either it is an error in your osm file or it is a error in the imposm library. I suggest to create an issue for it on the imposm3 repository: https://github.com/omniscale/imposm3

Feel free to reference / copy my snippet to reproduce the error.

**Comment by ImreSamu** [comment]
> So, either it is an error in your osm file 

imho:   .. this is not a valid osm file ..    ( lot of nodes duplicated )
see:  https://github.com/omniscale/imposm3/issues/210#issuecomment-541134725

**Comment by philippks** [comment]
thanks for your input @ImreSamu 

i close this issue then

**Comment by AmilaViduranga** [comment]
@ImreSamu Is there any way to fix those issues on osm file?
