### ISSUE TITLE
Planet file: Import process error

### ISSUE THREAD

**Issue by michelbio** [OSMNames/OSMNames#199]
I'm currently trying to import the planet pbf file, but hitting a wall in terms of this error:

```
[2020-06-09T07:52:06+02:00] 0:23:19 [error] caching relation: IO error: /tmp/imposm3/relations/000003.log: No space left on device
[2020-06-09T07:52:06+02:00] 0:23:19 [error] caching relation: IO error: /tmp/imposm3/relations/000003.log: No space left on device
[2020-06-09T07:52:06+02:00] 0:23:19 [error] caching relation: IO error: /tmp/imposm3/relations/000003.log: No space left on device
[2020-06-09T07:52:06+02:00] 0:23:19 [error] caching relation: IO error: /tmp/imposm3/relations/000003.log: No space left on device
[2020-06-09T07:52:06+02:00] 0:23:19 [error] caching relation: IO error: /tmp/imposm3/relations/000003.log: No space left on device
[2020-06-09T07:52:06+02:00] 0:23:19 [error] caching relation: IO error: /tmp/imposm3/relations/000003.log: No space left on device
[2020-06-09T07:52:06+02:00] 0:23:19 [error] caching relation: IO error: /tmp/imposm3/relations/000003.log: No space left on device
[2020-06-09T07:52:06+02:00] 0:23:19 [progress] 23m19s C: 8421000/s (6060677693) N:  208700/s (150226396) W: 1013000/s (669024729) R:      0/s (7848426)
[2020-06-09T10:05:32+02:00] 2:36:45 [step] Finished: Reading OSM data in 2h36m45.06820555s
[2020-06-09T10:05:32+02:00] 2:36:45 [step] Starting: Importing OSM data
[2020-06-09T10:05:32+02:00] 2:36:45 [step] Starting: Writing OSM data
[2020-06-09T10:05:35+02:00] 2:36:47 IO error: lock /tmp/imposm3/coords/LOCK: already held by process
Traceback (most recent call last):
  File "./run.py", line 30, in <module>
    run()
  File "./run.py", line 23, in run
    import_osm()
  File "/osmnames/osmnames/import_osm/import_osm.py", line 13, in import_osm
    import_pbf_file()
  File "/osmnames/osmnames/import_osm/import_osm.py", line 54, in import_pbf_file
    "-overwritecache",
  File "/osmnames/osmnames/logger.py", line 30, in logged_check_call
    check_call(parameters)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['imposm', 'import', '-connection', 'postgis://osm@postgres/osm', '-mapping', '/osmnames/osmnames/import_osm/mapping.yml', '-dbschema-import', 'public', '-read', '/osmnames/data/import/planet-latest.osm.pbf', '-write', '-overwritecache']' returned non-zero exit status 1.
```

There's more than enough storage available:
```
overlay         1.8T   88G  1.7T   6% /media/storage-2TB/data/docker/overlay2/5e7af49823040bca2c1e76dca82f6bd53e2feb25f951556baed55b09731d798c/merged
shm             256M  8.0K  256M   1% /media/storage-2TB/data/docker/containers/77db3cf4a855707994eaae09c0146dfbec99cf2294c3eaea8cda9a57c07d391f/mounts/shm
```

Which is on Ubuntu 18 with 32GB RAM and 8 core CPU.

What am I doing wrong, or how could I fix this?

**Comment by sfkeller** [comment]
Looks pretty much like an error in imposm which is probably triggerd by the data input (no of relations on temp device?).
Don't know if there's an imposm parameter to adjust.
If you're really want to get around this you probably have to try imposm separately with same parameters, and (if reproducable) open an issue at imposm repo.

**Comment by michelbio** [comment]
Hi @sfkeller appreciate the reply. Currently I'm testing the same import with a smaller data set. Instead of planet.osm.pbf, I'm importing South America. It seems to have started the write process (to the db) which to me is an indication that it runs as expected.

Perhaps the planet file is too big with the current settings. I even set the shm size for both dockers to 8GB each (without an effect for the planet import).

**Comment by ScanuNicco** [comment]
I'm having the same error trying to import us-latest.osm.pbf from geofabrik.de

**Comment by egorpavlikhin** [comment]
The issue is because the docker-compose uses tmpfs, which is an in-memory drive. You are not running out of disk space you are running out of memory. The import process requires a ridiculous amount of space - more than 100 Gb.

You can work around this by simply modifying two lines in docker-compose.yml

```
  osmnames:
    build: .
    volumes:
      - .:/osmnames
      - ./data:${DATA_DIR}
      - ./tmp # add this
    depends_on:
      - postgres
    #tmpfs: /tmp - comment this out
    env_file: .env
```
