### ISSUE TITLE
Cannot find file_pbf

### ISSUE THREAD

**Issue by ThomasCartier** [OSMNames/OSMNames#239]
Hi,

Steps:
1) download a country pbf
2) `git clone https://github.com/OSMNames/OSMNames.git`
3) mv the country.pbf in OSMNAmes/data/import
4)  make sure docker and docker-compose are installed (debian stable)
5) run `docker-compose run --rm osmnames`
6) fail with the following:

```
Creating osmnames_osmnames_run ... done
skip database init, since it is already initialized
2024-05-17 10:44:37,127 - INFO - skip wikipedia import, since table already exists
2024-05-17 10:44:37,127 - INFO - skip pbf download since PBF_FILE env is defined: country.pbf
2024-05-17 10:44:37,132 - INFO - run imposm import -connection postgis://osm@postgres/osm -mapping /osmnames/osmnames/import_osm/mapping.yml -dbschema-import public -read /osmnames/data/import/country.pbf -write -overwritecache
[2024-05-17T10:44:37+02:00] 0:00:00 [step] Starting: Imposm
[2024-05-17T10:44:37+02:00] 0:00:00 [step] Starting: Reading OSM data
[2024-05-17T10:44:37+02:00] 0:00:00 opening PBF file: open /osmnames/data/import/country.pbf: no such file or directory
Traceback (most recent call last):
  File "/osmnames/run.py", line 30, in <module>
    run()
  File "/osmnames/run.py", line 23, in run
    import_osm()
  File "/osmnames/osmnames/import_osm/import_osm.py", line 13, in import_osm
    import_pbf_file()
  File "/osmnames/osmnames/import_osm/import_osm.py", line 47, in import_pbf_file
    logged_check_call([
  File "/osmnames/osmnames/logger.py", line 30, in logged_check_call
    check_call(parameters)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['imposm', 'import', '-connection', 'postgis://osm@postgres/osm', '-mapping', '/osmnames/osmnames/import_osm/mapping.yml', '-dbschema-import', 'public', '-read', '/osmnames/data/import/country.pbf', '-write', '-overwritecache']' returned non-zero exit status 1.
ERROR: 1
```

my env file:
```
# default config for psql
PGHOST=postgres
PGUSER=osm
PGPASSWORD=osm

# timezone e.g. for python logger
TZ=Europe/Paris

DATA_DIR=/osmnames/data/
PBF_FILE=country.pbf

# Skips additional information from Wikipedia
SKIP_WIKIPEDIA=True

```

I don't understand, may someone help ?

Thanks

**Comment by ThomasCartier** [comment]
After two reboots, it ended up working. Well..
